/// Flutter icons BrandIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrandIcons
///      fonts:
///       - asset: fonts/BrandIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BrandIcons {
  BrandIcons._();

  static const _kFontFam = 'BrandIcons';
  static const String? _kFontPkg = null;

  static const IconData game21 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamefullcourt = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamev2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamev3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamev4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kingofthecourt = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
